### ISSUE TITLE
Create swap flow

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#107]
Create a new flow to swap tokens. From finance, clicking in the +New transfer button the modal should add a new option 'Swap tokens' 'Swap tokens using Uniswap v3' 

When this option is clicked, will open a new window like credit delegation with the fields:

- Token Input 
Select the token to swap from
(select like now in credit delegation)

- Amount
Amount of tokens to swap

- Token Output
Select the token to swap to 
(select like now in credit delegation)

When these fields are filled will create a new proposal with the action associated to swap the tokens.

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/113
 
 
Remaining tasks:
- Disable the +AddAction btn.
- Fix margins on the review swap screen.

**Comment by valentinnavalos** [comment]
Remaining tasks have been completed.

PR: https://github.com/Libree/frontend/pull/117

**Comment by ialberquilla** [comment]
I'm getting an error filling the first form


![Image](https://github.com/Libree/frontend/assets/974720/682624c3-d2b5-427e-8ef0-c89075e634e4)

**Comment by valentinnavalos** [comment]
Try it with this changes: https://github.com/Libree/frontend/pull/121.

On my localhost, it seems to be working fine.

**Comment by ialberquilla** [comment]
I'm getting the same error

**Comment by valentinnavalos** [comment]
Ok. Does the error appear when you fill the form, or when the form is been rendered?

**Comment by ialberquilla** [comment]
After filling out the form and clicking next

**Comment by valentinnavalos** [comment]
I restored the code to how it was before. It should be working.

PR: https://github.com/Libree/frontend/pull/123.

**Comment by ialberquilla** [comment]
Still same 🥴

**Comment by valentinnavalos** [comment]
I wanna cry. Its weird because i am not getting any error.

**Comment by ialberquilla** [comment]
Error is thrown here at ReviewWithoutLinks component because startDate is NaN


![Image](https://github.com/Libree/frontend/assets/974720/cc7c4645-7915-4bb9-8534-a920e4462b2a)

But checking this stepper and comparing it with the credit delegationstepper, <DefineProposal /> is missing? I think should be first a step to create the proposal where start date and other values are set to then get them at Review step

**Comment by valentinnavalos** [comment]
Ok. After comparing them, i added the two missing steps at swap flow. 
Let me know if the error persists.

PR: https://github.com/Libree/frontend/pull/127

**Comment by ialberquilla** [comment]
It works! a minor bug in the actions, amount is missing


![Image](https://github.com/Libree/frontend/assets/974720/10468e99-46c1-4504-ad38-5cf1cfa0b00f)

**Comment by valentinnavalos** [comment]
Awesome! I set `getEquivalentAmount()` to return the same amount as the "From" amount value. I think we should refactor this fn soon to return on-chain equivalent amounts, instead of the current behavior.

PR: https://github.com/Libree/frontend/pull/131

**Comment by ialberquilla** [comment]
That didn't work. Actually it was correct before, we don't need to calculate the amount out now, will be calculated on execution.

Just revert to the previous change should be ok



![Image](https://github.com/Libree/frontend/assets/974720/6b4819a8-1a75-4798-8184-60880a8a3a1e)
