### ISSUE TITLE
Empty fields dashboard

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#108]
When a dao is new, all the fields are empty

![Image](https://github.com/Libree/frontend/assets/974720/20a4f76b-bda7-470f-8d47-f7a0aa11dc54)

We should add a 0 as treasury amount, show 'No active groups yet' below active groups and 'No active investments yet' below investments

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/112

**Comment by ialberquilla** [comment]
Now it is not loading data, this dao has deposits and groups and nothing is shown

https://staging.libree.xyz/#/daos/mumbai/0xb6844cdcddf495d6558314febbb471ac838dd04b/dashboard

![Image](https://github.com/Libree/frontend/assets/974720/b1a71bbe-5d3f-4e0b-9de4-0aea343c011f)

**Comment by ialberquilla** [comment]
Was a connection problem in my side, works OK
