### ISSUE TITLE
Create provide liquidity flow

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#115]
Create a new flow to provide liquidity to Uniswap.

- Create a new entry in the finance transfer modal 'Provider liquidity' : 'Provide liquidity to Uniswap v3'
- Add a form to provide liquidity with the following fields: 
            - Token0  (Dropdown with tokens to select)
            - Deposit Amount (Amount of tokens of toke 0)
            - Token1 (Dropdown with tokens to select)
            - Deposit Amount  Amount (Amount of tokens of toke 0)
            - Fee tier Select with options 0.01%, 0.05%, 0,3%, 1%
            - Min price: number
            - Max Price: number

- Once this form is filled, as always will create a proposal

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/118

**Comment by ialberquilla** [comment]
Getting the same error as swap



![Image](https://github.com/Libree/frontend/assets/974720/187885b4-e4d0-487f-bf49-075ff439cb9a)
