### ISSUE TITLE
Add NFTs to dashboard

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#119]
Change the dashboard to add supports to NFTs, instead of showing Proposals Add a new Title 'Your NFTs'

![Image](https://github.com/Libree/frontend/assets/974720/396c9128-ab1b-4df5-adee-d5e803b7a36d)

- If there are no NFTs in the treasury show 'No NFTs yet'
- If there are NFTs show a preview of the NFT

Add a button below the card to see all the NFTS
![Image](https://github.com/Libree/frontend/assets/974720/a91df1ad-5cbe-49a4-a9f6-6a2dd059eb71)

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/124
