### ISSUE TITLE
Create 'Create budget Allocation' flow

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#120]
Create a new entry in finance + New transfer called 'Create budget allocation plan' subtitle: 'Assing fixed budgets to specific groups and protocols'

When this option is clicked a form will be opened as usual where several 'Asset allocation' Cards similar that swaps where several swaps can be created adding + add another swap

Each action will have: 

- Protocol. (Select with [Uniswap, Aave, PWN]) 'This is the destination protocol where you want to allocate this budget
- Token (Select token)
- Token amount: Number (Amount you want to allocate to the protocol)
- Group [Select with groups name available] 'This is the group that will be in charge of managing this budget'

**Comment by valentinnavalos** [comment]
Done.

PR: https://github.com/Libree/frontend/pull/129

**Comment by ialberquilla** [comment]
Looks great! There is a minor bug in the actions. Group manager name should be shown instead of the number


![Image](https://github.com/Libree/frontend/assets/974720/1632ff19-67a7-4266-9476-f66908948f20)

**Comment by valentinnavalos** [comment]
Fixed here: https://github.com/Libree/frontend/pull/131
