### ISSUE TITLE
Create marketplace page

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#134]
Create a new page that will be on/marketplace

This page will show a view with a list of open funding opportunities with a list like this

![Image](https://github.com/Libree/frontend/assets/974720/0d184e56-3b86-428d-8fac-ef489f10a53f)

Instead of Latest transfers use Open opportunities

And use mock data for the two first rows.

With this mock data

![Image](https://github.com/Libree/frontend/assets/974720/be81c4c3-9aae-4228-839a-b1d912b457cb)

And one button with the title + Get Funded

That will open a modal with two options: 

Collateralized borrowing
Borrow against your NFT or tokens 

Raise funding
Raise capital by selling your DAO governance tokens

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/138

**Comment by ialberquilla** [comment]
The modal that opens in marketplace


![Image](https://github.com/Libree/frontend/assets/974720/e130795f-a77e-46a3-a143-301dc1e31325)

Should have two options as the finance modal


![Image](https://github.com/Libree/frontend/assets/974720/8d5cb5a3-1dd7-4bfc-8008-14cd670ad568)

**Comment by valentinnavalos** [comment]
Fixed: https://github.com/Libree/frontend/pull/146
