### ISSUE TITLE
Dashboard changes

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#136]
Change the section to the right to NFTs:

- Change the title to Latest activity using the same style that your NFTs
- Remove button 
- Remove treasury value
- Resize to the same height to your NFTs

![Image](https://github.com/Libree/frontend/assets/974720/79a9a8ac-e1cd-40f1-9fae-6ed66686cf22)

Change dashboard section

- Change the legend to below the chart
- Add treasury value above the chart 
- Add new group button clicking it will redirect to /community/create-group
- Add new transfer button from the previous section

![Image](https://github.com/Libree/frontend/assets/974720/10c87b01-0606-4535-8ca6-933693846dd5)

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/142
