### ISSUE TITLE
Remove checks confirm page

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#140]
Remove pages on confirmation page when a dao is created 

![Image](https://github.com/Libree/frontend/assets/974720/1a554ecb-ab1e-4642-aa08-d045aaafe997)

This page should only show the details, and deploy your dao should be always active, without the need to check this checkboxes. We should remove them from the page

**Comment by valentinnavalos** [comment]
Done. PR: https://github.com/Libree/frontend/pull/152
