### ISSUE TITLE
Change plugins descriptions

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#151]
Change plugin descriptions on createUnity from

![Image](https://github.com/Libree/frontend/assets/974720/c2393f95-2af5-445f-9721-756ee58cd8e0)

to 

Sub-governance
Create groups within the DAO and delegate in them certain tasks of investments e.g. Grant allocation, Operational budget or Credit analysis

Vaults
Allocate a specific budget to certain strategies or groups. Organise your investments and limiting exposures

Credit Delegation
Leverage your Treasury: secure your yield in AAVE as you invest it in other projects, DAOs or lending products 

Uniswap
Complete swaps or provide liquidity to Uniswap pools without taking your treasury outside you DAO

**Comment by valentinnavalos** [comment]
Done.

PR: https://github.com/Libree/frontend/pull/153
