### ISSUE TITLE
Create fund a project flow

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#155]
- Create a new button in Marketplace to the left to the other called '+ Fund an opportunity'

When this button is clicked will open a form with two steps:

Step 1) Form with two select fields:

- Source of funding: Select with options [DAO treasury, Aave borrow)
- Collateral type: select with options [ERC20 token, NFT token]

Step 2) This form will show different fields depending on what was selected in Step 1

If er20 is selected: 

- Collateral address: Select with available coins, same that in credit delegation
- Collateral amount; Number
- Principal asset: Select with available coins, same that in credit delegation
- Loan amount: number
- Loan yield; Number
- Duration (in days): Number
- Expiration (in days): Number
- Borrower: address type field
- Is Persistent: Select [Yes, No]

If NFT is selected: 

- Collateral address: Address field
- Collateral id; Number
- Principal asset: Select with available coins, same that in credit delegation
- Loan amount: number
- Loan yield; Number
- Duration (in days): Number
- Expiration (in days): Number
- Borrower: address type field
- Is Persistent: Select [Yes, No]

Then for both, if Aave borrow is selected a select: Interest rate type [Stable, variable]

**Comment by ialberquilla** [comment]
Fund an oportunity button should be the same color that get funded


![Image](https://github.com/Libree/frontend/assets/974720/09735764-6431-4f39-ba5f-ea65b3e78844)

**Comment by ialberquilla** [comment]
After filling in the fields and clicking next, should create a proposal, nothing is happening



![Image](https://github.com/Libree/frontend/assets/974720/66b03f3a-8c08-458f-87b9-8446f3e437ab)

**Comment by valentinnavalos** [comment]
Fixed here: https://github.com/Libree/frontend/pull/159

**Comment by ialberquilla** [comment]
I'm getting an error creating the proposal, after filling the name and description, it fails


![Image](https://github.com/Libree/frontend/assets/974720/87b136e2-265b-4811-bc0f-38711ab9a21a)

**Comment by ialberquilla** [comment]
If NFT is selected in the first page, collateral address should be a text field like borrower


![Image](https://github.com/Libree/frontend/assets/974720/03e147cd-e6f8-4f73-aa44-73e5bb20839a)

**Comment by valentinnavalos** [comment]
Fixed here: https://github.com/Libree/frontend/pull/166

**Comment by ialberquilla** [comment]
Collateral address is empty when NFT is selected as collateral


![Image](https://github.com/Libree/frontend/assets/974720/a847de32-7d53-4c71-a874-a591fdab9b48)

**Comment by valentinnavalos** [comment]
Fixed here: https://github.com/Libree/frontend/pull/170

**Comment by ialberquilla** [comment]
Build fails

`2:11:27 PM 08/17/2023: src/utils/encoding.ts(191,9): error TS2769: No overload matches this call.
2:11:27 PM 08/17/2023: The last overload gave the following error.
2:11:27 PM 08/17/2023: Argument of type '"makeOffer"' is not assignable to parameter of type '"upgradeToAndCall"'.
2:11:27 PM 08/17/2023: error Command failed with exit code 2.`

**Comment by valentinnavalos** [comment]
I do not understand this error. Because Pwn.ts has the types necessary to makeOffer option (here: https://github.com/Libree/frontend/blob/develop/packages/web-app/src/typechain-types/Pwn.ts#L87)  but it use the last option that is 'upgradeToAndCall' option (here at line 94: https://github.com/Libree/frontend/blob/develop/packages/web-app/src/typechain-types/Pwn.ts#L94). it do not use 'makeOffer' option. what should i do?

**Comment by ialberquilla** [comment]
> I do not understand this error. Because Pwn.ts has the types necessary to makeOffer option (here: https://github.com/Libree/frontend/blob/develop/packages/web-app/src/typechain-types/Pwn.ts#L87) but it use the last option that is 'upgradeToAndCall' option (here at line 94: https://github.com/Libree/frontend/blob/develop/packages/web-app/src/typechain-types/Pwn.ts#L94). it do not use 'makeOffer' option. what should i do?

I'll take a look to that. Looks like it's not getting the correct function

**Comment by ialberquilla** [comment]
The problem was that makeOffer only takes 1 argument (an object) instead of the fields of the object, should be fixed here https://github.com/Libree/frontend/pull/171
