### ISSUE TITLE
Add PWN plugin card

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#157]
Create a new card on choose plugins section for pwn

![Image](https://github.com/Libree/frontend/assets/974720/ecc4ef63-73ec-4209-bc54-85a1c4ab9f33)

With title PWN 

Description: Access to a collateralized peer-to-peer lending market to fund opportunities or get funded

**Comment by valentinnavalos** [comment]
Done. PR: https://github.com/Libree/frontend/pull/160
