### ISSUE TITLE
Add functions to interact with backend

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#158]
Create functions to write, read and delete loan offers from API.

The API base URL is https://marketplace-backend-iota.vercel.app//loan-offer

- Create a function to add loan offers. POST method and data: 
```
{
    "collateralCategory": 0,
    "collateralAddress": "0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa",
    "collateralId": 0,
    "collateralAmount": 1000,
    "loanAssetAddress": "0xe9DcE89B076BA6107Bb64EF30678efec11939234",
    "loanAmount": 1000,
    "loanYield": 5,
    "duration": 1000,
    "expiration": 0,
    "borrower": "0x0000000000000000000000000000000000000000",
    "lender": "0x75f25C7f75992b17EEC14B7e702BD4b55C763f49",
    "isPersistent": false,
    "nonce": "0xb81415eeea3b749577614cd7eee7670471ea30e96b9c7aba53f4dcb8576be57f"
}
```

- Create a function to get all loan offers: GET method at `https://marketplace-backend-iota.vercel.app/loan-offer`
- Create a function to delete loan offers: DELETE method at `https://marketplace-backend-iota.vercel.app/loan-offer/{loanID}`

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/161
