### ISSUE TITLE
Marketplace changes

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#162]
We need to make some changes in the marketplace to look like this screenshot

![Image](https://github.com/Libree/frontend/assets/974720/757a75a9-c549-4b86-87d1-8b376e8f57de)

- [x] Add lending borrowing tab to filter the table format that will be shown in the future
- [x] Add a select with collateralized lending now only this will be available
- [x] A table with the fields shown
- [x] Fill the data of the table with the values that came from /loan-offer API. Use token address to get token symbol and icon as is done in treasury

**Comment by valentinnavalos** [comment]
@ialberquilla what data should display the collateralized lending select?

**Comment by ialberquilla** [comment]
This tab should shown the data that is on the screenshot, values comes from API GET `https://marketplace-backend-iota.vercel.app//loan-offer`

**Comment by valentinnavalos** [comment]
https://github.com/Libree/frontend/pull/177

**Comment by ialberquilla** [comment]
Looooooooks great!

Some small changes

- Move open opportunities to the top
- Move lending/borrowing to the right
- Remove old opportunities



![Image](https://github.com/Libree/frontend/assets/974720/8838fa90-0ed1-445c-b464-69f824800ab7)

**Comment by valentinnavalos** [comment]
https://github.com/Libree/frontend/pull/183
