### ISSUE TITLE
Add pwn typechain

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#163]
To connect frontend with the contracts we have the typing generated by the contract project under https://github.com/Libree/frontend/tree/develop/packages/web-app/src/typechain-types

We need to add the types for the new PWN plugin, following the steps:

- [x] CLone contracts project and install dependencies with npm install
- [x] Compile contracts with npx hardhat compile
- [x] This will create a new folder typechain-types
- [x] Copy the files generated under /factories/contracts/plugins/Pwn_factory__ts and /contracts/plugins/pwn/Pwn.ts to the frontend under typechain-types
- [x] FIx the paths in the paths inside the files to match the new directory from ../../../common to ./common

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/167
