### ISSUE TITLE
Create PWN installation function

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#164]
When #163 is finished we need to create the function to install the plugin on the dao. 

- [x]  If pwn plugin is selected create a new function like this to install the plugin on dao creation https://github.com/Libree/frontend/blob/826bfd328b99e1cd71ccf960b89a227e81b28aca/packages/web-app/src/context/createDao.tsx#L300

- [x] This function will be very similar we first need to add two needed addresses here https://github.com/Libree/frontend/blob/826bfd328b99e1cd71ccf960b89a227e81b28aca/packages/web-app/src/utils/config.ts#L12      const pwnSimpleLoanOfferAddress: string = '0xAbA34804D2aDE17dd5064Ac7183e7929E4F940BD'
    const pwnSimpleLoanAddress: string = '0x50160ff9c19fbE2B5643449e1A321cAc15af2b2C'

- [x] Then add a new pwn plugin address here https://github.com/Libree/frontend/blob/826bfd328b99e1cd71ccf960b89a227e81b28aca/packages/web-app/src/utils/config.ts#L36 0x88c107d4271dfda5bc173049db9005b54fd56541

- [x] And change the encode function with the new parameters 

```
    const hexBytes = ethers.utils.defaultAbiCoder.encode(
        ["address pwnSimpleLoanOfferAddress", "address pwnSimpleLoanAddress"],
        [
            CONTRACT_ADDRESSES[networkName].pwnSimpleLoanOfferAddress,
            CONTRACT_ADDRESSES[networkName].pwnSimpleLoanAddress
        ],
    );

    return {
        id: PLUGIN_ADDRESSES[networkName].pwn,
        data: hexToBytes(hexBytes),
    };

```

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/168
