### ISSUE TITLE
Create encodeLoanOfferAction

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#165]
To encode makeOffer function in pwn plugin and attach it to the proposal, we need to create a function to encode the call

- [x] Create a function like this call encondeMakeOffer https://github.com/Libree/frontend/blob/826bfd328b99e1cd71ccf960b89a227e81b28aca/packages/web-app/src/utils/encoding.ts#L150
- [x] WIll receive an offer of type Offer https://github.com/Libree/contracts/blob/3f3c8b9aec72ae13e2ac98f1c3db2c7a84c783b0/contracts/plugins/pwn/interfaces/IPWNSimpleLoanListOffer.sol#L8 and pluginAddress
- [x] Encode the function call with the factory imported at #163 and function name `makeOffer`

**Comment by valentinnavalos** [comment]
Done here: https://github.com/Libree/frontend/pull/169.

As i saw, then we should integrate this new function here https://github.com/Libree/frontend/blob/develop/packages/web-app/src/context/createProposal.tsx#L291 with proposal data. right?
