### ISSUE TITLE
Change app background

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#17]
Change app background from blue:

![Image](https://github.com/Libree/frontend/assets/974720/8dfaf941-ed9d-48a1-83b0-33b302edd167)

To a color like this 

![Image](https://github.com/Libree/frontend/assets/974720/b72054ed-8733-4a27-a7ae-90f132e8f3a4)

**Comment by ialberquilla** [comment]
Maybe @TCLIV can give the exact color

**Comment by TCLIV** [comment]
#33475b

<img width="1116" alt="Screenshot 2023-06-27 at 18 32 15" src="https://github.com/Libree/frontend/assets/71262733/9c0d6b90-3059-407c-a2c2-5d50fd5e270a">

**Comment by TCLIV** [comment]
#3D5570 big stripe and #33475b for the upper navigation bar

<img width="1003" alt="Screenshot 2023-06-27 at 18 43 32" src="https://github.com/Libree/frontend/assets/71262733/b33616f8-011f-4c48-86b5-fc021aafb90a">

**Comment by ialberquilla** [comment]
Also @TCLIV please paste here the logo image

**Comment by TCLIV** [comment]
<img width="200" alt="Screenshot 2023-06-27 at 20 14 54" src="https://github.com/Libree/frontend/assets/71262733/d484cdf9-8662-4566-a044-6b2ed2c639bc">
<img width="210" alt="Screenshot 2023-06-27 at 20 15 16" src="https://github.com/Libree/frontend/assets/71262733/eddcc544-1181-4e00-aea4-708765685363">

**Comment by TCLIV** [comment]
<img width="652" alt="Screenshot 2023-05-12 at 18 09 33" src="https://github.com/Libree/frontend/assets/71262733/946fd4dd-bd40-4629-847a-36529335f027">

**Comment by ialberquilla** [comment]
We have lost the 'Create from template title' in the last update @valentinnavalos

**Comment by valentinnavalos** [comment]
> We have lost the 'Create from template title' in the last update @valentinnavalos

Fixed: https://github.com/Libree/frontend/pull/21

**Comment by ialberquilla** [comment]
@TCLIV can you check? Everything looks good in the app?

**Comment by TCLIV** [comment]
Looks good but Icons are missing from the cards

**Comment by valentinnavalos** [comment]
> <img alt="Screenshot 2023-06-27 at 20 14 54" width="200" src="https://user-images.githubusercontent.com/71262733/249246843-d484cdf9-8662-4566-a044-6b2ed2c639bc.png"> <img alt="Screenshot 2023-06-27 at 20 15 16" width="210" src="https://user-images.githubusercontent.com/71262733/249246913-eddcc544-1181-4e00-aea4-708765685363.png">

@TCLIV do you have another img of the salary icon without the tag "salary icon 4725755" ?

**Comment by TCLIV** [comment]
<img width="237" alt="Screenshot 2023-07-03 at 14 06 54" src="https://github.com/Libree/frontend/assets/71262733/5caa1ade-11c1-49b6-833e-4b6bd7ced99a">

**Comment by valentinnavalos** [comment]
Done.

PR: https://github.com/Libree/frontend/pull/33
