### ISSUE TITLE
Loan offer change

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#180]
In the form to create a loan Offer at /marketplace/loan-offer

The collateral type can be NFT or Token, we need to change the behaviour when one of them are selected 

- If collateral type selected is Tokens -> change collateral field to a select with the available tokens
- IF collateral type selected is NFT -> change collateral field to input field to add and address

**Comment by valentinnavalos** [comment]
Done. https://github.com/Libree/frontend/pull/185
