### ISSUE TITLE
Loan offer card

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#181]
When a new loan offer is created using marketplace/loan-offer, the Action card should be refactor, to show each field in a row like is done in credit delegation action

![Image](https://github.com/Libree/frontend/assets/974720/df61ad40-001c-4dce-ac9e-1218e6538d3a)

![Image](https://github.com/Libree/frontend/assets/974720/bc0eb6e0-bb54-4c1d-8dfa-cc8d3b9a9856)

**Comment by valentinnavalos** [comment]
https://github.com/Libree/frontend/pull/186
