### ISSUE TITLE
Change finance page

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#24]
Change finance page to show always content even if the treasury is empty

Now when the treasury is empty a page is shown asking to deposit funds. Remove this page to always show the balance (top left) and 'New transfer' button

If there are not tokens Tokens and latest transfers sections won't be shown 

![Image](https://github.com/Libree/frontend/assets/974720/b89069fc-b366-43db-9723-531343ee11e1)

After this, add a new option in the modal that appears on clicking new Transfer add 

'Credit delegation'
'Create a proposal to delegate credit to other wallet'

**Comment by valentinnavalos** [comment]
Done. 

PR: https://github.com/Libree/frontend/pull/27
