### ISSUE TITLE
Create group detail page

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#26]
Create group detail page. From community/groups if a group is clicked will be redirect to a page with group details.

A page where group members will be listed

![Image](https://github.com/Libree/frontend/assets/974720/f15b6afe-8e50-4ea6-aacb-145a7ae10871)

With a button to add new members and an icon on each member to be removed

When add member is clicked will show a page to add the details of the members

![Image](https://github.com/Libree/frontend/assets/974720/b4194c23-241b-4ede-816e-dd26d8e1007a)

Then on clicking next will create a proposal to be voted. This behavior can be checked on other similar components like https://github.com/Libree/frontend/blob/main/packages/web-app/src/pages/newWithdraw.tsx

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/29

**Comment by valentinnavalos** [comment]
STATUS: all references to withdrawn have been removed, as well as any unnecessary code. However, the handling of values with actions and useForm still needs to be fixed.
