### ISSUE TITLE
Deposit assets modal don't get values

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#31]
In finance page -> New transfer -> deposit assets

The modal for depositing assets is not getting the values, if new values are set, them are not changing

![Image](https://github.com/Libree/frontend/assets/974720/76e41b39-98aa-4c67-824c-a44f2348d992)

**Comment by valentinnavalos** [comment]
Fixed.

PR: https://github.com/Libree/frontend/pull/34

**Comment by ialberquilla** [comment]
@valentinnavalos  I've been testing it, but values are not being updated. If I change it and then try to use the values on submit, tokenAddress is always empty and amount always 100
