### ISSUE TITLE
Add actions to proposal

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#39]
When new members are added from the groups add members action, the proposal gets created, but there is not action associated

![Image](https://github.com/Libree/frontend/assets/974720/59f823c4-89be-4a53-b444-36924180e4e6)

The action should show the addresses that will be added to the group.

Also to create the group a name for the group should be provided in the first form, sorry my fault

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/42

**Comment by ialberquilla** [comment]
There is an error on this. When I try to create a new proposal to add a member, it gets an error 



![Image](https://github.com/Libree/frontend/assets/974720/649507e6-80d6-41f3-9929-980ce760819d)



![Image](https://github.com/Libree/frontend/assets/974720/41996053-bb64-4aa1-bcc3-4e4732e757ff)

**Comment by valentinnavalos** [comment]
Fixed.

PR: https://github.com/Libree/frontend/pull/56
