### ISSUE TITLE
Actions inputs are missing

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#49]
When a new credit delegation flow is created, a form is filled by the user, with the token, amount and wallet. These values should be added to the action fields to then be used here https://github.com/Libree/frontend/blob/372a66819d58821dff249b1ed1b70ca136df3988/packages/web-app/src/context/createProposal.tsx#L270

Right now only the name is provided, the fields in the form should be added to the action.

![Image](https://user-images.githubusercontent.com/974720/251504854-6380ae19-7a65-4dcd-a8c0-29a2f09af87d.png)

**Comment by valentinnavalos** [comment]
Fixed.

PR: https://github.com/Libree/frontend/pull/51
