### ISSUE TITLE
Create lending page

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#6]
Create a new page under finance/lending, with the following design using mock data

![Image](https://github.com/Libree/frontend/assets/974720/a998b428-ec8e-46e9-b8d4-6b3c12a268a4)

**Comment by valentinnavalos** [comment]
@ialberquilla this new page should be under ProtectedRoute?

**Comment by valentinnavalos** [comment]
@ialberquilla should this new page be under ProtectedRoute?

**Comment by ialberquilla** [comment]
> @ialberquilla should this new page be under ProtectedRoute?

Nope, same as groups or finance, everybody can see it even if is not a token holder

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/22
