### ISSUE TITLE
Add cards to proposal info

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#62]
When a proposal is created, before sending it and create the proposal, the card with the credit delegation can be shown attached to the proposal, but once the proposal is sent, in the detail and info tab the card is not shown

I added this decoded there, and the parameters are being returned correctly but still now show.

https://github.com/Libree/frontend/blob/1742d3be174c2f717c5a9fa085e64a222b6bb0e7/packages/web-app/src/pages/proposal.tsx#L280

to check this behavior this proposal can be used

http://localhost:3000/#/daos/mumbai/0xcb0ad058745a256b5b1d6d1a46fe85ef7306dbbb/governance/proposals/0xd483b4d753eb7958ea67a916817c2a7820908afb_0x0

![Image](https://user-images.githubusercontent.com/974720/252627913-294d89d1-115d-4f6f-920c-4c47496a8504.png)

**Comment by valentinnavalos** [comment]
STATUS: the parameters are returning as 'undefined'

**Comment by ialberquilla** [comment]
Shoud be fixed at #73

**Comment by valentinnavalos** [comment]
It is working as expected.
