### ISSUE TITLE
Delegation card fixes

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#63]
Remove (0%) 

![Image](https://github.com/Libree/frontend/assets/974720/6c446cf4-b8f7-4f77-b02d-79cc446061ea)

Start interest rate type with capital letter

![Image](https://github.com/Libree/frontend/assets/974720/57ce021f-75b5-4650-b4e2-34cda8379062)

**Comment by valentinnavalos** [comment]
Fixed.

PR: https://github.com/Libree/frontend/pull/74
