### ISSUE TITLE
List supported tokens

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#66]
Use the list of supported tokens created here https://github.com/Libree/frontend/pull/65

to use in forms where users have to provide the asset, to do it in a more friendly way.. 

In deposit, instead of pasting the contract address, create a select that will show the supported asset names, and when the user selects a name, set the address in the tokenAddress

The same is in the credit delegation flow, where the tokenAddress is specified.

**Comment by valentinnavalos** [comment]
Done.

PR: https://github.com/Libree/frontend/pull/72
