### ISSUE TITLE
Change buttons color

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#70]
I think buttons properties are inside ui-components if it possible to apply to all the buttons, change the default color, instead of blue to

Also the progress bar

![Image](https://user-images.githubusercontent.com/974720/252992559-4a855653-628f-41e5-9376-65452c4a544f.png)

**Comment by valentinnavalos** [comment]
Do you have the hexadecimal value of the color you want to change to?

And regarding the default color change, is it only for all buttons or for anywhere that color is used, including the progress bar?

**Comment by ialberquilla** [comment]
Yes, the hex color is #0ab6c0

Should be applied anywhere is used.

I think these colors are set into ui-componets which is linked to web-app with yarn link, so you'll need to run yarn build inside ui-components to see the changes in the app

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/80
