### ISSUE TITLE
Dashboard changes

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#75]
IN the current dashboard we need to do some changes

![Image](https://github.com/Libree/frontend/assets/974720/2399475e-3a0e-404b-8511-808cbae343ba)

Below the first card with the name and URL add the following

![Image](https://github.com/Libree/frontend/assets/974720/ee725203-9d7c-485a-a291-86bda7a3a95b)

A pie chart to show how funds are allocated, for now just a pie char that will show 100% treasury

A section to show groups created within the DAO; we can use mock data now

A section to show active investments, we can also use mock data, only showing Aave

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/79

**Comment by ialberquilla** [comment]
I don't see any change in dashboard. don't see the chart nor goups or investments




![Image](https://github.com/Libree/frontend/assets/974720/c6e25643-4fec-4cd6-aa7d-6176b1475a30)

**Comment by valentinnavalos** [comment]
Fixed.

PR: https://github.com/Libree/frontend/pull/83
