### ISSUE TITLE
Lending page changes

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#77]
Use the data get from aave created in this PR https://github.com/Libree/frontend/pull/76 to add Real data to /finance/lending page, doing some changes

- Remove Net APY field
- Add Total collateral field, with the data 
- Add Total Debt field, with the data
- Show health factor only with totalDebt >0 

You can use this dao address as example to get data 0x90f0b0afae1e82094776b1fc15fa70187d74e5a0

**Comment by valentinnavalos** [comment]
Done.

PR: https://github.com/Libree/frontend/pull/81

**Comment by ialberquilla** [comment]
This Dao has total debt == 0 and health factor is show

https://staging.libree.xyz/#/daos/mumbai/0xb6844cdcddf495d6558314febbb471ac838dd04b/finance/lending

**Comment by valentinnavalos** [comment]
PR: https://github.com/Libree/frontend/pull/84

**Comment by ialberquilla** [comment]
Still same

**Comment by ialberquilla** [comment]
My bad, it has debt but quite small
