### ISSUE TITLE
Submit DAO page

### ISSUE THREAD

**Issue by TCLIV** [Libree/frontend#86]
<img width="1131" alt="Screenshot 2023-07-18 at 16 12 50" src="https://github.com/Libree/frontend/assets/71262733/150a8ce6-23b4-4e25-abde-23ce914ab061">
-Este boton aparece como ya seleccionado (el formato)
-No hay boton para volver atras

**Comment by ialberquilla** [comment]
Not sure what you mean by button. To go back, you can edit on each group
