### ISSUE TITLE
Margenes

### ISSUE THREAD

**Issue by TCLIV** [Libree/frontend#88]
<img width="1329" alt="Screenshot 2023-07-18 at 16 13 14" src="https://github.com/Libree/frontend/assets/71262733/4ea57697-d95b-4a64-9a16-33f8c11de783">
Todas las paginas de creacion tendrian que tener el contenido de abajo la misma anchura que la de la navegacion

**Comment by ialberquilla** [comment]
I think this is related to mobile style right @valentinnavalos ? All the pages have the same margins

**Comment by valentinnavalos** [comment]
Yes. All the pages have the same design. 

On mobile devices, the content occupies the entire available width. As the transition is made to desktop view, the content adjusts to fill the width as shown in the image. In the meanwhile, the header always stays with full width.
