### ISSUE TITLE
Logo upload

### ISSUE THREAD

**Issue by TCLIV** [Libree/frontend#89]
<img width="402" alt="Screenshot 2023-07-18 at 16 13 32" src="https://github.com/Libree/frontend/assets/71262733/36aff704-273f-4d24-9e74-a2a465d42ae2">
Podemos hacer algo para que esto admita mas tamaños y lo ajuste automaticamente?

**Comment by ialberquilla** [comment]
Ahora mismo no, esa es una restricción de Aragon que se sube a IPFS
