### ISSUE TITLE
Add approval to deposit

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#91]
When a user deposits in the DAO, the allowance is not checked so if there is no approval the transaction will revert.

In this PR https://github.com/Libree/frontend/pull/90 I have implemented the approval, there is a TODO:

When the user deposits, if the allowance is lower than the amount to deposit, the label of the modal should change to Approve this will send the approval, change the label to waiting for the transaction to confirm, as is done to create a DAO, and then change again to deposit, also waiting for the transaction, when it is confirmed, close the modal and refresh the page

**Comment by valentinnavalos** [comment]
@ialberquilla how can i get the state of the tx? Should we make some tx handler here right?

https://github.com/Libree/frontend/blob/refactor/approval_deposit/packages/web-app/src/containers/transactionModals/DepositModal.tsx#L69

**Comment by ialberquilla** [comment]
Yes we should check that the transaction has been confirmed. Maybe we can create a tx handler in utils or and send the tx and handle the state like is done in the SDK

https://github.com/aragon/sdk/blob/40b83218411b26a42983d431a2c2fc4c4649e54b/modules/client/src/addresslistVoting/internal/client/methods.ts#L229

Changing the state from EXECUTING to DONE we can reuse this function to both approve and depost

**Comment by valentinnavalos** [comment]
Ok. I've created this PR to verify that the workflow is correct. Once its ok, i will make the tx handler at utils.
This approach if to avoid potential troubles.

PR: https://github.com/Libree/frontend/pull/97

**Comment by ialberquilla** [comment]
ok, added some comments there related with the tx handler, you can ignore it, but there is a  if(true

**Comment by valentinnavalos** [comment]
@ialberquilla  Is it ok that this approve() function to return a 0?

https://github.com/Libree/frontend/blob/develop/packages/web-app/src/hooks/useCreditDelegation.tsx#L43

**Comment by ialberquilla** [comment]
> @ialberquilla Is it ok that this approve() function to return a 0?
> 
> https://github.com/Libree/frontend/blob/develop/packages/web-app/src/hooks/useCreditDelegation.tsx#L43

It is returning the Tx to be used by a handler, actually await it is not needed, and maybe catch should return the error to let know the handler that the tx failed
