### ISSUE TITLE
Add groups names

### ISSUE THREAD

**Issue by ialberquilla** [Libree/frontend#93]
Change dashboard to show real data instead of mock data for groups names.

In this PR there is a new hook to get groups data. use it to fill the groups names in dashboard

https://github.com/Libree/frontend/pull/92

This dao address can be use as example, already has a group 0xb6844cdcddf495d6558314febbb471ac838dd04b

**Comment by valentinnavalos** [comment]
Done. 

PR: https://github.com/Libree/frontend/pull/98

**Comment by ialberquilla** [comment]
There is an error on building

 tsc && cross-env NODE_ENV=production node --max_old_space_size=16384 ../../node_modules/vite/bin/vite.js build --sourcemap true > build.txt
12:17:26 AM 07/20/2023: src/containers/smartContractComposer/components/contractAddressValidation.tsx(602,19): error TS7053: Element implicitly has an 'any' type because expression of type 'TransactionState.WAITING | TransactionState.SUCCESS | TransactionState.ERROR | TransactionState.APPROVING' can't be used to index type '{ WAITING: string; LOADING: string; SUCCESS: string; ERROR: string; }'.
12:17:26 AM 07/20/2023: Property '[TransactionState.APPROVING]' does not exist on type '{ WAITING: string; LOADING: string; SUCCESS: string; ERROR: string; }'.
12:17:26 AM 07/20/2023: src/containers/smartContractComposer/components/contractAddressValidation.tsx(654,24): error TS7053: Element implicitly has an 'any' type because expression of type 'TransactionState.WAITING | TransactionState.SUCCESS | TransactionState.ERROR | TransactionState.APPROVING' can't be used to index type '{ WAITING: undefined; LOADING: undefined; SUCCESS: Element; ERROR: undefined; }'.
12:17:26 AM 07/20/2023: Property '[TransactionState.APPROVING]' does not exist on type '{ WAITING: undefined; LOADING: undefined; SUCCESS: Element; ERROR: undefined; }'.
12:17:26 AM 07/20/2023: src/containers/transactionModals/publishModal.tsx(137,18): error TS7053: Element implicitly has an 'any' type because expression of type 'TransactionState' can't be used to index type '{ WAITING: string; LOADING: string; SUCCESS: string; ERROR: string; }'.
12:17:26 AM 07/20/2023: Property '[TransactionState.APPROVING]' does not exist on type '{ WAITING: string; LOADING: string; SUCCESS: string; ERROR: string; }'.
12:17:26 AM 07/20/2023: src/containers/transactionModals/publishModal.tsx(138,21): error TS7053: Element implicitly has an 'any' type because expression of type 'TransactionState' can't be used to index type '{ WAITING: undefined; LOADING: Element; SUCCESS: undefined; ERROR: Element; }'.
12:17:26 AM 07/20/2023: Property '[TransactionState.APPROVING]' does not exist on type '{ WAITING: undefined; LOADING: Element; SUCCESS: undefined; ERROR: Element; }'.

**Comment by valentinnavalos** [comment]
Fixed.

PR: https://github.com/Libree/frontend/pull/103

**Comment by ialberquilla** [comment]
This DAO is not showing active groups



![Image](https://github.com/Libree/frontend/assets/974720/cdd2b8c9-0397-4bb7-832d-9a0e5b70ca79)

**Comment by valentinnavalos** [comment]
@ialberquilla  Is there any way i could get those values on localhost? All the data (chart, investments and groups data) is currently empty.

**Comment by ialberquilla** [comment]
> @ialberquilla Is there any way i could get those values on localhost? All the data (chart, investments and groups data) is currently empty.

Yes you can, everything should be showing up. Did you connect the wallet and set up the env vars?

**Comment by valentinnavalos** [comment]
I do not have the env vars.

**Comment by valentinnavalos** [comment]
Done.

PR: https://github.com/Libree/frontend/pull/110
